image: rustlang/rust:nightly

variables:
  RUSTFLAGS: "-Dwarnings"
  CARGO_OPTIONS: "--all-targets --all-features"

.nextest_dependencies: &nextest_dependencies
  - curl -LsSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
  - cargo binstall cargo-nextest

build:nightly:
  stage: build
  before_script:
    - *nextest_dependencies
  script:
    - cargo nextest run $CARGO_OPTIONS
  artifacts:
    when: always
    reports:
      junit: ./target/nextest/default/junit.xml

# Based on https://github.com/taiki-e/cargo-llvm-cov#gitlab-ci
build:coverage:
  stage: build
  before_script:
    - *nextest_dependencies
  script:
    - cargo binstall cargo-llvm-cov
    - cargo llvm-cov nextest $CARGO_OPTIONS --ignore-filename-regex main.rs
    - cargo llvm-cov report --ignore-filename-regex main.rs --cobertura --output-path ./target/coverage.xml
  coverage: '/^TOTAL.*\s+([\d\.]+\%)/'
  artifacts:
    when: always
    reports:
      junit: ./target/nextest/default/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: ./target/coverage.xml

check:clippy:
  stage: build
  script:
    - rustup component add clippy
    - cargo clippy $CARGO_OPTIONS

check:format:
  stage: build
  script:
    - rustup component add rustfmt
    - cargo fmt --check
