[package]
name = "tunnel"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29"
num = "0.4"
rand = "0.9"

[dev-dependencies]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
